b# ===================================================================
# DECAP CMS YAPILANDIRMASI - Thepickonick Projesi için
# ===================================================================

# -------------------------------------------------------------------
# ARKA UÇ (BACKEND) AYARLARI
# -------------------------------------------------------------------
# Bu bölüm, CMS'in içeriği nereye kaydedeceğini ve kimlik doğrulamayı
# nasıl yapacağını belirler. [cite: 170, 171]
# -------------------------------------------------------------------
backend:
  # 'git-gateway', Netlify'ın kimlik doğrulama (Identity) hizmetiyle
  # GitHub deponuza erişimini sağlar. [cite: 178, 531] Bu sayede, CMS'e giren
  # her kullanıcının GitHub hesabı olmasına gerek kalmaz.
  name: git-gateway
  # 'branch', içeriklerin GitHub deponuzun hangi dalına (branch)
  # kaydedileceğini belirtir. Genellikle 'main' veya 'master' kullanılır. [cite: 175, 532]
  branch: main

# -------------------------------------------------------------------
# MEDYA (GÖRSEL vb.) DOSYALARININ YÖNETİMİ
# -------------------------------------------------------------------
# Bu ayarlar, CMS üzerinden yüklenen görsellerin veya diğer dosyaların
# depoda nereye kaydedileceğini ve sitede nasıl gösterileceğini belirler. [cite: 181]
# -------------------------------------------------------------------
# 'media_folder', CMS üzerinden yüklenen dosyaların GitHub deponuzda
# hangi klasöre kaydedileceğini belirtir. [cite: 188]
media_folder: "images/uploads"

# 'public_folder', yüklenen medyaların web sitenizde hangi yoldan
# erişilebilir olacağını belirtir. [cite: 196] Örneğin, buraya yüklenen bir görselin
# linki '/images/uploads/gorsel.jpg' şeklinde olacaktır.
public_folder: "/images/uploads"

# -------------------------------------------------------------------
# KOLEKSİYONLAR (COLLECTIONS)
# -------------------------------------------------------------------
# Burası CMS'in en önemli kısmıdır. Sitenizdeki farklı içerik türlerini
# burada tanımlarsınız. [cite: 204, 205] Örneğin "Blog Yazıları", "Hakkımızda Sayfası" vb.
# -------------------------------------------------------------------
collections:
  # --- KOLEKSİYON 1: BLOG YAZILARI ---
  # Bu koleksiyon, sitenizdeki tüm blog yazılarını yönetmek içindir.
  # "Folder Collection" tipindedir, yani tek bir klasördeki çok sayıda
  # benzer dosyayı yönetir.
  - name: "blog"
    [cite_start]label: "Blog Yazıları" # CMS arayüzünde bu koleksiyonun görünecek adı. [cite: 216]
    [cite_start]folder: "_posts" # Blog yazılarının depoda saklanacağı klasör. [cite: 217] Jekyll için bu klasörün adı '_posts' olmalıdır.
    [cite_start]create: true # Kullanıcıların bu koleksiyonda yeni yazı oluşturmasına izin verir. [cite: 217]
    
    # 'slug', yeni bir yazı oluşturulduğunda dosya adının nasıl
    # olacağını belirleyen bir şablondur. [cite: 218] Jekyll, blog yazıları için
    # 'YIL-AY-GÜN-başlık' formatını zorunlu kılar. [cite: 566]
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    
    # 'editor', bu koleksiyona özel editör ayarları yapmanızı sağlar.
    # Jekyll, 'Liquid' adında bir şablonlama dili kullandığı için Decap CMS'in
    # canlı önizleme özelliği düzgün çalışmaz. Bu nedenle kapatıyoruz. [cite: 568, 569]
    editor:
      preview: false
      
    # 'fields', her bir blog yazısının hangi alanlardan oluşacağını tanımlar.
    # Bu alanlar, CMS'deki editör ekranında bir form olarak görünür. [cite: 218]
    fields:
      - { label: "Yazi Basligi", name: "title", widget: "string" }
      - { label: "Yayinlanma Tarihi", name: "date", widget: "datetime" }
      - { label: "Kategori", name: "category", widget: "select", options: ["SOCIAL MEDIA", "PRODUCT REVIEW", "TECHNOLOGY"] }
      - { label: "Öne Çikan Görsel", name: "thumbnail", widget: "image" }
      - { label: "Özet (Excerpt)", name: "excerpt", widget: "text", hint: "Yazının ana sayfada görünecek kısa özeti." }
      - { label: "Yazi İçeriği", name: "body", widget: "markdown" }
# ... fields bölümünün diğer alanları ...
     - { label: "Öne Cikan Yazi?", name: "featured", widget: "boolean", default: false, hint: "Bu kutucuğu işaretlerseniz, yazı ana sayfadaki 'Öne Çıkan Gönderiler' bölümünde görünür." }
     - { label: "Yazi İçeriği", name: "body", widget: "markdown" }
# ...
  # --- KOLEKSİYON 2: SAYFALAR ---
  # Bu koleksiyon, "Hakkımızda", "İletişim" gibi tekil ve sabit sayfaları
  # yönetmek içindir. "File Collection" tipindedir. 
  - name: "pages"
    label: "Sabit Sayfalar" # CMS arayüzünde görünecek ad.
    
    # 'files' koleksiyonu, klasördeki tüm dosyaları değil, sadece
    # belirttiğiniz spesifik dosyaları düzenlemenizi sağlar. [cite: 679]
    files:
      - label: "Hakkımızda Sayfası"
        name: "about" # Bu sayfanın CMS'teki kimliği.
        file: "about.md" # Düzenlenecek olan dosyanın tam yolu.
        fields:
          - { label: "Sayfa Başlığı", name: "title", widget: "string" }
          - { label: "Sayfa İçeriği", name: "body", widget: "markdown" }
          
      - label: "İletişim Sayfası"
        name: "contact"
        file: "contact.md" # Projenizde bu dosyayı oluşturmanız gerekir.
        fields:
          - { label: "Sayfa Başlığı", name: "title", widget: "string" }
          - { label: "Giriş Metni", name: "intro_text", widget: "markdown" }
          - { label: "E-posta Adresi", name: "email", widget: "string" }
          - { label: "Telefon Numarası", name: "phone", widget: "string" }