# ===================================================================
# DECAP CMS CONFIGURATION
# ===================================================================

# -------------------------------------------------------------------
# BACKEND CONFIGURATION
# -------------------------------------------------------------------
# This section defines where the CMS will save content and how it will
# handle authentication.
# -------------------------------------------------------------------
backend:
  # 'git-gateway' connects to your GitHub repo via Netlify's Identity service.
  # This allows users to log in to the CMS without needing a GitHub account.
  name: git-gateway
  # The branch where content will be saved in your GitHub repository.
  branch: main

# -------------------------------------------------------------------
# MEDIA FILE MANAGEMENT
# -------------------------------------------------------------------
# These settings determine where uploaded media files are stored in the
# repository and how they are accessed on the live site.
# -------------------------------------------------------------------
media_folder: "images/uploads"
public_folder: "/images/uploads"

# -------------------------------------------------------------------
# COLLECTIONS
# -------------------------------------------------------------------
# This is the core of the CMS. It defines the different content types
# for your site, such as "Blog Posts" or "Pages".
# -------------------------------------------------------------------
collections:
  # --- COLLECTION 1: BLOG POSTS ---
  - name: "blog"
    label: "Blog Posts" # The display name for this collection in the UI.
    folder: "_posts" # The path to the folder where documents are stored. For Jekyll, this must be '_posts'.
    create: true # Allows users to create new documents in this collection.
    
    # The filename template for new documents. Jekyll requires this format for posts.
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    
    # Editor-specific settings for this collection.
    # Preview is disabled for compatibility with Jekyll's Liquid templating.
    editor:
      preview: false
      
    # Defines the fields for each document in this collection.
    # These appear as a form in the editor UI.
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "select", options: ["SOCIAL MEDIA", "PRODUCT REVIEW", "TECHNOLOGY"] }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Excerpt", name: "excerpt", widget: "text", hint: "A short summary of the post that will appear on the main page." }
      - { label: "Featured Post?", name: "featured", widget: "boolean", default: false, hint: "Check this box to feature this post on the homepage." }
      - { label: "Body", name: "body", widget: "markdown" }

  # --- COLLECTION 2: PAGES ---
  # This collection manages single, static pages like "About" or "Contact".
  - name: "pages"
    label: "Pages" # The display name for this collection in the UI.
    
    # 'files' collections let you edit specific, individual files.
    files:
      - label: "About Page"
        name: "about"
        file: "about.md"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Page Content", name: "body", widget: "markdown" }
          
      - label: "Contact Page"
        name: "contact"
        file: "contact.md"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Intro Text", name: "intro_text", widget: "markdown" }
          - { label: "Email Address", name: "email", widget: "string" }
          - { label: "Phone Number", name: "phone", widget: "string" }
